//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_REST_Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int UserID { get; set; }
        public string PrimerApellido { get; set; }
        public string SegundoApellido { get; set; }
        public string PrimerNombre { get; set; }
        public string OtrosNombres { get; set; }
        public string PaisEmpleo { get; set; }
        public string TipoIdentificacion { get; set; }
        public string NumeroIdentificacion { get; set; }
        public string CorreoElectronico { get; set; }
        public string Area { get; set; }
        public Nullable<System.DateTime> FechaHoraRegistro { get; set; }
        public Nullable<System.DateTime> FechaHoraActualizado { get; set; }
        public string Estado { get; set; }
        public string FechaIngreso { get; set; }
    }
}
